Switch from `const` to `using`. Get errors in vite
With syntax only change get

```
[plugin:remix-route-exports] This experimental syntax requires enabling the parser plugin: "explicitResourceManagement". (17:2)
/Users/jfsiii/repos/remix-vite-pages-rpc/app/routes/_index.tsx:21:2
15 |    console.log({ MY_JSON_VAR, MY_RPC, MY_SERVICE_A, MY_SERVICE_B, MY_VAR, MY_VAR_A });
16 |    const resultA = await MY_SERVICE_A.fetch("http://0.0.0.0");
17 |    using counter = await MY_RPC.getCounter();
   |    ^
18 |    console.log(await counter.value);
19 |    console.log(await counter.increment(4));
```

After updating vite.config.ts with

```
  esbuild: {
    target: "es2022",
  },
```

get
```
TypeError: Object not disposable
    at __typeError (/Users/jfsiii/repos/remix-vite-pages-rpc/app/routes/_index.tsx:8:9)
    at __using (/Users/jfsiii/repos/remix-vite-pages-rpc/app/routes/_index.tsx:16:40)
    at loader (/Users/jfsiii/repos/remix-vite-pages-rpc/app/routes/_index.tsx:21:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.callRouteLoader (/Users/jfsiii/repos/remix-vite-pages-rpc/node_modules/@remix-run/server-runtime/dist/data.js:66:16)
    at async /Users/jfsiii/repos/remix-vite-pages-rpc/node_modules/@remix-run/router/dist/router.cjs.js:4230:21
    at async callLoaderOrAction (/Users/jfsiii/repos/remix-vite-pages-rpc/node_modules/@remix-run/router/dist/router.cjs.js:4295:16)
    at async Promise.all (index 1)
    at async callDataStrategyImpl (/Users/jfsiii/repos/remix-vite-pages-rpc/node_modules/@remix-run/router/dist/router.cjs.js:4170:17)
    at async callDataStrategy (/Users/jfsiii/repos/remix-vite-pages-rpc/node_modules/@remix-run/router/dist/router.cjs.js:3703:19)
    at async loadRouteData (/Users/jfsiii/repos/remix-vite-pages-rpc/node_modules/@remix-run/router/dist/router.cjs.js:3678:19)
    at async queryImpl (/Users/jfsiii/repos/remix-vite-pages-rpc/node_modules/@remix-run/router/dist/router.cjs.js:3523:20)
    at async Object.query (/Users/jfsiii/repos/remix-vite-pages-rpc/node_modules/@remix-run/router/dist/router.cjs.js:3416:18)
    at async handleDocumentRequest (/Users/jfsiii/repos/remix-vite-pages-rpc/node_modules/@remix-run/server-runtime/dist/server.js:223:15)
    at async requestHandler (/Users/jfsiii/repos/remix-vite-pages-rpc/node_modules/@remix-run/server-runtime/dist/server.js:142:18)
    at async /Users/jfsiii/repos/remix-vite-pages-rpc/node_modules/@remix-run/dev/dist/vite/cloudflare-proxy-plugin.js:70:25
```